### ISSUE TITLE
Progress ?

### ISSUE THREAD

**Issue by marcus-sa** [ngxs-labs/async-storage-plugin#26]
Been waiting for this for quite some time, how's the progress so far?
Tried to find it on NPM, but still yet no publish has been done, even though it looks like it's quite finished.

**Comment by splincode** [comment]
@markwhitfeld Could you publish the package as alpha?

**Comment by markwhitfeld** [comment]
@splincode This is a labs project, you are welcome to publish it as an `@alpha` tagged release.

**Comment by splincode** [comment]
https://www.npmjs.com/package/@ngxs-labs/async-storage-plugin
